### PR TITLE
addition.cpp close #67

### LINKED ISSUE #67: Addition of two ploynomials using linked list (C)
Addition of two ploynomials using linked list in C

### PR DESCRIPTION
**Pull request by ashishugi**
Improved Indentation

### CODE REVIEW

**Comment by rishabhgarg25699** [comment]
@ashishugi Add close #issue statement

**Review by rishabhgarg25699 — CHANGES_REQUESTED** [review]
@ashishugi Extra files.

**Comment by ashishugi** [comment]
where should I use it??

**Comment by ashishugi** [comment]
close #67

**Comment by ashishugi** [comment]
close #179

**Comment by rishabhgarg25699** [comment]
@ashishugi You have to add only addition.cpp but in this PR two files are extra - dijkastra.cpp and scc.cpp. Please remove them or close the PR and open new PR with only one file.

**Pull request closed without merging**
