### PR TITLE
Create matrix_chain_multiply.cpp

### PR DESCRIPTION
**Pull request by anuratb**
Finding the position of the parentheses that is the order of multiplication of matrices so that least number of scalar multiplications take place using dynamic programming

### CODE REVIEW

**Comment by anuratb** [comment]
Swapping without using a third variable using bitwise operation xor

**Comment by rishabhgarg25699** [comment]
Add the issue link with close #issue statement

**Comment by anuratb** [comment]
close #https://github.com/rishabhgarg25699/Competitive-Programming/issues/127
close
#https://github.com/rishabhgarg25699/Competitive-Programming/issues/128

**Comment by rishabhgarg25699** [comment]
@Seedot65 One issue, one PR

**Pull request closed without merging**
