### PR TITLE
#233

### LINKED ISSUE #233: Kadane Algorithm In C
Can you assign this to me?

### PR DESCRIPTION
**Pull request by ivaibhavjindal**
Closes #233

### CODE REVIEW

**Comment by rishabhgarg25699** [comment]
@ivaibhavjindal Please make another PR

**Comment by ivaibhavjindal** [comment]
@rishabhgarg25699 Should I include both the files in new PR or only .c file?

**Comment by rishabhgarg25699** [comment]
@ivaibhavjindal  only .c file

**Comment by ivaibhavjindal** [comment]
@rishabhgarg25699 Okay Thanks! I've created the new PR #248

**Pull request closed without merging**
