### PR TITLE
Searching and Sorting algorithms in Python

### LINKED ISSUE #156: Sorting Algorithms in Python
Various searching algorithms include - 
* Selection sort
* Bubble sort
* Insertion sort
* Quick sort
* Merge sort
* Heap sort
* Radix sort
* Shell sort

### PR DESCRIPTION
**Pull request by RashakDude**
Closes #156

### CODE REVIEW

**Comment by RashakDude** [comment]
This Pull request addresses to Issue #146. Please review the files :)

**Comment by rishabhgarg25699** [comment]
@RashakDude Take input from user

**Comment by rishabhgarg25699** [comment]
@RashakDude Add closes #issue statement

**Comment by RashakDude** [comment]
> @RashakDude Take input from user

Okay I will update the files :)

**Comment by RashakDude** [comment]
@rishabhgarg25699 Done 👍

**Comment by RashakDude** [comment]
@rishabhgarg25699 I have added the sorting algorithms directing to issue #156

**Review by rishabhgarg25699 — APPROVED** [review]

**Pull request merged**
