### PR TITLE
Added Bubble Sort Algorithm in C

### LINKED ISSUE #51: Implement bubble sort in C
I would like to take up this issue.

### PR DESCRIPTION
**Pull request by ayush-krishna**
Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in wrong order.
close #51

### CODE REVIEW

**Comment by ayush-krishna** [comment]
close #51

**Review by rishabhgarg25699 — CHANGES_REQUESTED** [review]
@ayush-krishna remove an extra file .DS_Store

**Comment by ayush-krishna** [comment]
done

**Comment by ayush-krishna** [comment]
@rishabhgarg25699  made the changes

**Review by rishabhgarg25699 — APPROVED** [review]

**Pull request merged**
