### PR TITLE
SUBSETS OF A SET

### LINKED ISSUE #116: Finding subsets of a set in o(2^n) complexity

### PR DESCRIPTION
**Pull request by yashica-patodia**
closed #116 
this algorithm finds the subsets of a set implementing backtracking,with O(2^N) complexity.
Basically,at every i th element of the set we have two options either to choose or not to choose the element .

### CODE REVIEW

**Review by rishabhgarg25699 — CHANGES_REQUESTED** [review]
@yashica-patodia Take input from user

**Comment by yashica-patodia** [comment]
@rishabhgarg25699 made the requested changes

**Review by rishabhgarg25699 — CHANGES_REQUESTED** [review]
Remove a.out file

**Comment by yashica-patodia** [comment]
@rishabhgarg25699 made the changes

**Review by rishabhgarg25699 — APPROVED** [review]

**Pull request merged**
