### PR TITLE
Solved smallest subset problem

### LINKED ISSUE #195: Smallest subset of an array whose sum equals that of the given value in Order of n
Assign me this please

### PR DESCRIPTION
**Pull request by srijanakde2001**
close #195

### CODE REVIEW

**Review by rishabhgarg25699 — CHANGES_REQUESTED** [review]
@srijanakde2001 Variation of Nim/variationofnim.py  Two extra files.

**Comment by srijanakde2001** [comment]
Is it ok now? Or how do i make the changes?

**Comment by rishabhgarg25699** [comment]
@srijanakde2001 Not correct. See in the file changed. You deleted a file.

**Comment by srijanakde2001** [comment]
Screenshot (2)
Screenshot (3)
See in these two screenshots, in Solved Nim it has only the code for Nim, and in Solved Subset it has only the code for Subset. I deleted the rest of the files. What should be done?

**Comment by rishabhgarg25699** [comment]
@srijanakde2001  Sorting Algos/countsort.cpp  this is the extra file. Close the PR and open new pR

**Pull request closed without merging**
