### PR TITLE
Shoelace Formula to find area of polygon

### LINKED ISSUE #125: Finding area of a polygon in C++ and JAVA
Using shoelace formula to find the area  of a polygon with n ordered vertices

### PR DESCRIPTION
**Pull request by mayank-kumarr**
close #125 
The code makes use of Shoelace formula to find the area of any sided polygon whose coordinates are given, in time complexity O(n).

### CODE REVIEW

**Comment by rishabhgarg25699** [comment]
@mayankkumar1205 Add closes #issue statement

**Comment by mayank-kumarr** [comment]
@rishabhgarg25699 Done!!

**Comment by rishabhgarg25699** [comment]
@mayankkumar1205 Put the issue number instead of PR number. And remove the KMP file in Shoelace Formula PR

**Comment by mayank-kumarr** [comment]
@rishabhgarg25699 Did both the changes!

**Comment by rishabhgarg25699** [comment]
@mayankkumar1205 Read the info part of the telegram group. Where it is written you had to write the closed issue #issue. In comment, also I wrote the correct pattern.

**Comment by mayank-kumarr** [comment]
@rishabhgarg25699  Sorry, I didn't get that. I am new to this! I have made the change now.

**Review by rishabhgarg25699 — APPROVED** [review]

**Pull request merged**
