### PR TITLE
Generalized Linked List

### LINKED ISSUE #155: Generalized Linked List
A generalized linked list program in which one can insert or delete a node at all the three, the beginning, user-chosen position at middle or at the end.

I want to take this issue.

### PR DESCRIPTION
**Pull request by SayantanBanerjee16**
This is a CPP program on a generalized linked list that can insert as well as delete node at the beginning, middle or at the end. The user is asked at each step through menu-driven options.
close #155

### CODE REVIEW

**Comment by rishabhgarg25699** [comment]
@SayantanBanerjee16 Please add a close statement.

**Comment by SayantanBanerjee16** [comment]
> @SayantanBanerjee16 Please add a close statement.

Sorry sir, didn't get you. What you want me to do?

**Comment by rishabhgarg25699** [comment]
@SayantanBanerjee16 Read line 32
https://gist.github.com/rishabhgarg25699/7b880d28b77b10383096458a115780af

**Comment by SayantanBanerjee16** [comment]
close #155

**Pull request merged**
