### PR TITLE
Implementation of KMP Algorithm

### PR DESCRIPTION
**Pull request by mayank-kumarr**
closed issue #139 
KMP algorithm searches for a pattern in a given text and gives the index number of those as output. The worst-case time complexity of this algorithm is O(n).

### CODE REVIEW

**Comment by rishabhgarg25699** [comment]
@mayankkumar1205 Add closes #issue statement

**Comment by mayank-kumarr** [comment]
@rishabhgarg25699 Added!!

**Comment by rishabhgarg25699** [comment]
@mayankkumar1205 Same #issue number not #pull number

**Comment by mayank-kumarr** [comment]
@rishabhgarg25699 Made the change

**Pull request merged**
