### PR TITLE
Create DSU_implementation.cpp

### LINKED ISSUE #167: DSU(Disjoint Set Union) Implemtatation
I would like to work on this issue

### PR DESCRIPTION
**Pull request by Roopam-mishra**
Created a dsu implementation in cpp as per the issue number #167 
close #167

### CODE REVIEW

**Comment by Roopam-mishra** [comment]
Created Segmented Sieve in cpp as per the issue number #175

**Comment by rishabhgarg25699** [comment]
@Roopam-mishra One PR, one issue.  
Add close #issue statement.

**Comment by Roopam-mishra** [comment]
close #175

**Comment by Roopam-mishra** [comment]
@rishabhgarg25699  what else I need to do?

**Comment by Roopam-mishra** [comment]
Do I need to delete Segmented_Sieve.cpp ?

**Comment by Roopam-mishra** [comment]
close #167

**Review by rishabhgarg25699 — APPROVED** [review]

**Pull request merged**
